### ISSUE TITLE
Error after pasting redirect URL

### ISSUE THREAD

**Issue by nvjkmr** [sahilprasad/tumblr-terminal#1]
Not sure if it is an error due to inappropriate URL or something else, but even after this error, the command was working, as I tested posting to my blog.

```
Traceback (most recent call last):
  File "/usr/local/bin/tumblr", line 9, in <module>
    load_entry_point('tumblr-terminal==0.3', 'console_scripts', 'tumblr')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2229, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/tumblr_terminal/__init__.py", line 24, in <module>
    blog_url = client.info()['user']['name']
  File "/usr/local/lib/python2.7/dist-packages/pytumblr/__init__.py", line 36, in info
    return self.send_api_request("get", "/v2/user/info")
  File "/usr/local/lib/python2.7/dist-packages/pytumblr/__init__.py", line 536, in send_api_request
    return self.request.get(url, params)
  File "/usr/local/lib/python2.7/dist-packages/pytumblr/request.py", line 36, in get
    resp, content = client.request(url, method="GET", redirections=False)
  File "/usr/local/lib/python2.7/dist-packages/oauth2/__init__.py", line 687, in request
    connection_type=connection_type)
  File "/usr/local/lib/python2.7/dist-packages/httplib2/__init__.py", line 1609, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "/usr/local/lib/python2.7/dist-packages/httplib2/__init__.py", line 1351, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "/usr/local/lib/python2.7/dist-packages/httplib2/__init__.py", line 1307, in _conn_request
    response = conn.getresponse()
  File "/usr/lib/python2.7/httplib.py", line 1136, in getresponse
    response.begin()
  File "/usr/lib/python2.7/httplib.py", line 453, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python2.7/httplib.py", line 409, in _read_status
    line = self.fp.readline(_MAXLINE + 1)
  File "/usr/lib/python2.7/socket.py", line 480, in readline
    data = self._sock.recv(self._rbufsize)
socket.error: [Errno 104] Connection reset by peer

```

**Comment by sahilprasad** [comment]
Hey @VijayKumarHackr! The error seems to indicate that Tumblr's servers are not responding to the request. This is most likely due to the URL being malformed in some manner, but could also be a result of any number of changes that have occurred since this repository was last updated.

I'll try to put some time aside this weekend to get this project back into working shape! Till then, I'll leave this open.

**Comment by nvjkmr** [comment]
@sahilprasad I'm willing to work on this project. I wanted to build exactly what you tried to do here, but left it incomplete. I just completed reading your code. I feel that I can take your project further.

**Comment by sahilprasad** [comment]
Sure thing! But I feel responsible as the owner of this project to maintain the code that I put out into the world, at least to a level permitting minimal intended functionality, so I'll update the repo first and then welcome any PRs :) 

Does that sound good?

**Comment by nvjkmr** [comment]
I'm still wondering whether to make changes by forking it or start from scratch. Because, I am planning to change a lot of things. First thing is the commands. And second is the name of the repository, since I have a cooler name.

**Comment by nvjkmr** [comment]
what do you think about this: https://github.com/vijaykumarhackr/teblr/

**Comment by sahilprasad** [comment]
Looks dope, man! It's exactly what I wanted to do initially. Great job! :+1:
